resources:
  - name: demo_repo
    type: GitRepo
    configuration:
      gitProvider: my_github                       # <-- replace with your integration
      path: katcosgrove/devops-101-workshop    # <-- replace with your repository name
      branches:
        include: master

  - name: demo_build
    type: Image
    configuration:
      registry: art                                # <-- replace with your artifactory integration
      sourceRepository: docker_local               # <-- required if registry is Artifactory
      imageName: katcsandbox.jfrog.io/demo-docker-local/docker-demo # < -- replace with your image path and name
      imageTag: latest
      autoPull: true
      
  - name: demo_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: demo_build
      buildNumber: 1    

  - name: demo_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: demo_build
      buildNumber: 1
      

pipelines:
  - name: pipeline_demo
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: demo_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: katcsandbox.jfrog.io/demo-docker-local/docker-demo  # replace with your image path and name
          dockerImageTag: ${run_number}
          inputResources:
            - name: demo_repo
          integrations:
            - name: art                            # <-- replace with your artifactory integration

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: docker-local
          integrations:
            - name: art                            # <-- replace with your artifactory integration
          inputSteps:
            - name: docker_build
          outputResources:
            - name: demo_build

      - name: publish_dbp_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: dbp_build_info

      - name: promote_demo_build
        type: PromoteBuild
        configuration:
          targetRepository: demo-docker
          integrations:
            - name: art
          inputResources:
            - name: demo_build_info
          outputResources:
            - name: demo_promoted_build_info
